<a href="https://colab.research.google.com/github/JAYASHREEUSHA/Basicplots/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ANN

Import the libaries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.9.2'

Data preprocessing

Import dataset

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding categorical data

Label Encoding the ''Gender''

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2] =le.fit_transform(x[:,2])
print(x)



[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot encoding the 'Geography' column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])] ,remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the traning set, test set 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0) 

Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

Building the ANN

Initializing the ANN

In [ ]:
ann=tf.keras.models.Sequential()


Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1 ,activation='sigmoid'))

Training the ANN

Compiling the ANN

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

Training the ANN on the training set

In [ ]:
ann.fit(x_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5210 - accuracy: 0.7950
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4667 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4495 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4358 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4325 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.7961
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4273 - accuracy: 0.7965
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4247 - accuracy: 0.7971
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4219 - accura

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]])>0.5))

1/1 [==============================] - 0s 109ms/step
[[0.02544489]]


Predivting thte test set results

In [ ]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1595    0]
 [ 405    0]]


0.7975