<a href="https://colab.research.google.com/github/JAYASHREEUSHA/Basicplots/blob/main/Linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating matrix using array feature in numpy

In [1]:
import numpy as np

A=np.array([[1,2,7,2],[5,8,-9,0],[6,-7,11,12]])
print("A=",A)

A= [[ 1  2  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


Matrix using Additon and multiplication

In [6]:
import numpy as np
import numpy.linalg as la

A=np.array([[1,2],
            [3,4]])

Adet=la.det(A)
print(Adet)

B=np.array([[-1,3,0],
            [2,1,-5],
            [1,4,-2]])
Bdet=la.det(B)
print(Bdet)

-2.0000000000000004
-21.00000000000001


Matrix multiplication

In [4]:

C=np.dot(A,B)
print("A*B =",C)


A*B = [[  3  -2]
 [-11   6]]


Martix operations

In [3]:
import numpy as np

A=np.array([[0,1],[-2,-3]])
B=np.array([[1,-0],[3,-2]])
C=A+B
print("A+B=",C)
C=A-B
print("A-B=",C)

A+B= [[ 1  1]
 [ 1 -5]]
A-B= [[-1  1]
 [-5 -1]]


Transpose of matrix

In [5]:

import numpy as np

A=np.array([[1,3,7,2],
            [5,8,-9,0],
            [6,-7,11,12]])
print("A="); print(A)
Atr=np.transpose(A)
print("Transpose of A=")
print(Atr)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


Egien value

In [8]:
import numpy as np                                 
import numpy.linalg as la

A=np.array([[0,1],
            [-2,-3]])
Aeig, v=la.eig(A)
print(Aeig)

[-1. -2.]


Inverse of matrix

In [7]:
import numpy as np
import numpy.linalg as la

A=np.array([[1,2],[3,4]])

Ainv=la.inv(A)
print(Ainv)

B=np.array([[-1,3,0],[2,1,-5],[1,4,-2]])

Binv=la.inv(B)
print(Binv)


[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


Solving Linear equations

In [9]:
import numpy as np
import numpy.linalg as la

A=np.array([[1,2],
            [3,4]])
b=np.array([[5],
            [6]])

Ainv=la.inv(A)
x=Ainv.dot(b)
print(x)




[[-4. ]
 [ 4.5]]


Alternative method 

In [10]:
x=np.linalg.solve(A,b)
print(x)

[[-4. ]
 [ 4.5]]
