<a href="https://colab.research.google.com/github/JAYASHREEUSHA/Basicplots/blob/main/Mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regression model (multiple_linear_regression)

In [ ]:
#Import libaries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

#Import dataset

df=pd.read_csv('32_Murder_victim_age_sex.csv')

x1 =df["Victims_Above_50_Yrs"].mean()
df["Victims_Above_50_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_10_15_Yrs"].mean()
df["Victims_Upto_10_15_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_10_Yrs"].mean()
df["Victims_Upto_10_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_15_18_Yrs"].mean()
df["Victims_Upto_15_18_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_18_30_Yrs"].mean()
df["Victims_Upto_18_30_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_30_50_Yrs"].mean()
df["Victims_Upto_30_50_Yrs"].fillna(x1, inplace = True)
x=df.iloc[:,4:-1].values
y=df.iloc[:,-1].values


#Splitting the dataset into trainset and testset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

#Traning the simple Linear Regression model
regressor=LinearRegression()
regressor.fit(x_train,y_train)
LinearRegression()


#Predicting the test set and train set
y_pred=regressor.predict(x_test)
x_pred=regressor.predict(x_train)


#Applying the linear regression model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred =regressor.predict(x_test)
print("MAE", mean_absolute_error(y_test, y_pred))
print("MSE", mean_squared_error(y_test, y_pred))
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))
print("r2 score", r2_score(y_test, y_pred))
r2 = r2_score(y_test, y_pred)



MAE 25.261278739723018
MSE 2214.281981347136
RMSE 47.05615774101341
r2 score 0.9832595992643997


Classification model ( Support_vector_machine)



In [ ]:
#importing the libarires
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC


#importing the dataset
df=pd.read_csv('32_Murder_victim_age_sex.csv')

# finding the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x1 =df["Victims_Above_50_Yrs"].mean()
df["Victims_Above_50_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_10_15_Yrs"].mean()
df["Victims_Upto_10_15_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_10_Yrs"].mean()
df["Victims_Upto_10_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_15_18_Yrs"].mean()
df["Victims_Upto_15_18_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_18_30_Yrs"].mean()
df["Victims_Upto_18_30_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Upto_30_50_Yrs"].mean()
df["Victims_Upto_30_50_Yrs"].fillna(x1, inplace = True)
x1 =df["Victims_Total"].mean()
df["Victims_Total"].fillna(x1, inplace = True)

x=df.iloc[:,5:-1].values
y=df.iloc[:,-1].values


#Feature scaling
le = LabelEncoder()
y = le.fit_transform(y)


#Predicting a new result
xtrain,xtest, ytrain, ytest = train_test_split(x,y,test_size=35, random_state=1)


# training the model
regressor = SVC(kernel='linear',random_state=1)
regressor.fit(xtrain,ytrain)


# predicting the values
ypred = regressor.predict(xtest)


# accuracy score
cm = confusion_matrix(ytest,ypred)
print(cm)
print(accuracy_score(ytest,ypred))

[[1 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
0.17142857142857143
